# Тестирование FastAPI эндпоинтов

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/api/v1/clicker/
Accept: text/html

###

GET http://127.0.0.1:8000/api/v1/products/
Accept: text/html
